### ISSUE TITLE
Disable editing for ID field

### ISSUE THREAD

**Issue by karenmajewicz** [geobtaa/geoblacklight_admin#100]
Once a record has been created, it is not possible alter the ID in Solr.  However, GEOMG allows a user to edit this field.

We should make the field uneditable after the record is created.

**Comment by ewlarson** [comment]
Transferred this from GEOMG repo.

**Comment by ewlarson** [comment]
How frequently would you need this capability? — I ask because it opens a pretty significant can of worms... primarily, if you change a document's ID (also the friendlier_id in Kithe terminology), you break all the item's associated relationships: assets, references, etc because those all map to that friendlier_id value.

Maybe that's just bad data architecure/design? But, as things currently stand, we'd really want a a "service" of some kind to handle editing this particular field, so those relationships are properly re-key'd too.

Perhaps this ID-changing "service" is just another Bulk Action in the application?

**Comment by ewlarson** [comment]
Okay. I've fixed this behavior in the application. 

![Image](https://github.com/user-attachments/assets/a72692b2-551b-44e9-bc93-d7e86200a404)
