### ISSUE TITLE
Create custom export just for analytics

### ISSUE THREAD

**Issue by karenmajewicz** [geobtaa/geoblacklight_admin#37]
We are exporting all records once per month to populate our Tableau analytics board. We don't need all fields for this, so let's create a customized export. Fields to include:

- [ ] Title
- [ ] Provider
- [ ] Resource Class
- [ ] Index Year
- [ ] Spatial Coverage
- [ ] ID

Maybe useful:

- [ ] Language
- [ ] Creator
- [ ] Resource Type
- [ ] Theme
- [ ] Bounding Box (maybe)
- [ ] Member Of
- [ ] Is Part Of
- [ ] Access Rights
- [ ] Publication State

Are any download or outlinks needed?

**Comment by ewlarson** [comment]
Okay. We'll pull this data directly from the database. I'll write an endpoint to grab the data as CSV.

**Comment by karenmajewicz** [comment]
I transferred this issue from the old repo which is how it showed up again.

This list of metadata fields feels a bit long still, so I will ask Mark what fields he actually is using.

**Comment by vinegar-tom** [comment]
For the Tableau viz, I'm currently using:

- Title
- Provider
- Resource Class
- Resource Type
- Index Year
- Spatial Coverage
- B1G Image
- ID
- Download

These are ones that are currently loaded into the viz, since they were part of previous iterations—but they're no longer used on any views. @karenmajewicz, are we okay with scrapping these, or do we want to keep them, in case they are useful in the future?

- Language
- Subject
- Theme
- Keyword

**Comment by karenmajewicz** [comment]
The language field is normalized, so it would be good to keep it. Subject, Theme, and Keyword are so variable that they are not all that useful.  

@vinegar-tom How are you using B1G Image?

**Comment by vinegar-tom** [comment]
I'm mostly using "Download" to match with the Matomo data for download URLs, but there isn't always a match. When I checked, around 5-6 other fields might contain the URL to match with Matomo—but the one with the most matches (other than "Download") was "B1G Image".

I'm not able to use all of the possible fields, since it's how I'm joining the two data sources, and it doesn't work well with more than 1 "if X is null, then Y" step. Also, some of the download URLs from Matomo entirely don't match with any of the data from the export.
